name = "FamilyComputer"
uuid = "38ed752b-27bd-4a6b-b923-5110ccc36214"
authors = ["dr666m1 <skndr666m1@gmail.com>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SimpleDirectMediaLayer = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
